---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: localhost
  connection: local
  become: True
  vars_files:
    - ../var/opnfv.yml
  pre_tasks:
    - name: Load flavor variables
      include_vars:
        file: ../file/{{ XCI_FLAVOR }}/flavor-vars.yml
  roles:
    - create-libvirt-environment
  tasks:
    - name: Ensure ssh key has correct permissions
      file:
        path: "../scripts/vm/{{ item }}"
        mode: 0600
      with_items:
        - id_rsa_for_dib
        - id_rsa_for_dib.pub

- hosts: opnfv
  become: True
  vars_files:
    - ../var/opnfv.yml
    - ../var/{{ ansible_os_family }}.yml
  tasks:
    - name: Load flavor variables
      include_vars:
        file: ../file/{{ XCI_FLAVOR }}/flavor-vars.yml

    - set_fact:
        libvirt_dns: |-
          {%- set libvirt_dns = [] %}
          {%- for network in networks %}
            {%- set _ = libvirt_dns.append(network['ip']) %}
          {%- endfor %}
          {{- libvirt_dns }}

    - name: Add libvirt dns
      lineinfile:
        state: present
        line: "nameserver {{ item }}"
        path: /etc/resolv.conf
      with_items: "{{ libvirt_dns }}"

    - name: Ensure root has correct authorized_key
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '{{ OPNFV_RELENG_PATH }}/xci/scripts/vm/id_rsa_for_dib.pub') }}"

    - name: Install required build packages for PIP
      package:
        name: "{{ pip_build_required_packages }} + {{ virt_required_packages }}"
        state: latest

    - name: install virtualbmc
      pip:
        name: virtualbmc

